/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 818d30eadfda6f2995c2e89234eaf64e)
interface __BaseEnv_Env {
	SPOTIFY_TOKENS: KVNamespace;
	RATE_LIMIT: RateLimit;
	SPOTIFY_CLIENT_ID: string;
	SPOTIFY_CLIENT_SECRET: string;
	SPOTIFY_REFRESH_TOKEN: string;
	SPOTIFY_CONNECT_SECRET: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	GUESTBOOK_ADMIN_TOKEN: string;
	ROOM: DurableObjectNamespace /* Room */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SPOTIFY_CLIENT_ID" | "SPOTIFY_CLIENT_SECRET" | "SPOTIFY_REFRESH_TOKEN" | "SPOTIFY_CONNECT_SECRET" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_CHAT_ID" | "GUESTBOOK_ADMIN_TOKEN">> {}
}
